// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Infrastructure.Data;

#nullable disable

namespace TechStore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Account.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("CPUs", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Colors", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplayCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("DisplayCoverages", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplaySize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DisplaySizes", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplayTechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("DisplayTechnologies", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Formats", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.RAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RAMs", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Resolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Resolutions", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.SSDCapacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SSDCapacities", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Sensitivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Sensitivities", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Types", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.VideoCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("VideoCards", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountOfPurchases")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Headphone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("HasMicrophone")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Headphones", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Keyboard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("FormatId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Keyboards", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CPUId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayCoverageId")
                        .HasColumnType("int");

                    b.Property<int>("DisplaySizeId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayTechnologyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RAMId")
                        .HasColumnType("int");

                    b.Property<int?>("ResolutionId")
                        .HasColumnType("int");

                    b.Property<int>("SSDCapacityId")
                        .HasColumnType("int");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("VideoCardId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CPUId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DisplayCoverageId");

                    b.HasIndex("DisplaySizeId");

                    b.HasIndex("DisplayTechnologyId");

                    b.HasIndex("RAMId");

                    b.HasIndex("ResolutionId");

                    b.HasIndex("SSDCapacityId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TypeId");

                    b.HasIndex("VideoCardId");

                    b.ToTable("Laptops", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Mouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWireless")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("SensitivityId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("SellerId");

                    b.HasIndex("SensitivityId");

                    b.HasIndex("TypeId");

                    b.ToTable("Mice", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.SmartWatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("SellerId");

                    b.ToTable("SmartWatches", (string)null);
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Television", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("DisplaySizeId")
                        .HasColumnType("int");

                    b.Property<int?>("DisplayTechnologyId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ResolutionId")
                        .HasColumnType("int");

                    b.Property<int?>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("DisplaySizeId");

                    b.HasIndex("DisplayTechnologyId");

                    b.HasIndex("ResolutionId");

                    b.HasIndex("SellerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Televisions", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.Account.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Client", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Headphone", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Brand", "Brand")
                        .WithMany("BrandHeadphones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Color", "Color")
                        .WithMany("ColorHeadphones")
                        .HasForeignKey("ColorId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.Client", "Seller")
                        .WithMany("Headphones")
                        .HasForeignKey("SellerId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Type", "Type")
                        .WithMany("TypeHeadphones")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Seller");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Keyboard", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Brand", "Brand")
                        .WithMany("BrandKeyboards")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Color", "Color")
                        .WithMany("ColorKeyboards")
                        .HasForeignKey("ColorId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Format", "Format")
                        .WithMany("FormatKeyboards")
                        .HasForeignKey("FormatId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.Client", "Seller")
                        .WithMany("Keyboards")
                        .HasForeignKey("SellerId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Type", "Type")
                        .WithMany("TypeKeyboards")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Format");

                    b.Navigation("Seller");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Laptop", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Brand", "Brand")
                        .WithMany("BrandLaptops")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.CPU", "CPU")
                        .WithMany("CPULaptops")
                        .HasForeignKey("CPUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Color", "Color")
                        .WithMany("ColorLaptops")
                        .HasForeignKey("ColorId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplayCoverage", "DisplayCoverage")
                        .WithMany("DisplayCoverageLaptops")
                        .HasForeignKey("DisplayCoverageId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplaySize", "DisplaySize")
                        .WithMany("DisplaySizeLaptops")
                        .HasForeignKey("DisplaySizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplayTechnology", "DisplayTechnology")
                        .WithMany("DisplayTechnologyLaptops")
                        .HasForeignKey("DisplayTechnologyId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.RAM", "RAM")
                        .WithMany("RAMLaptops")
                        .HasForeignKey("RAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Resolution", "Resolution")
                        .WithMany("ResolutionLaptops")
                        .HasForeignKey("ResolutionId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.SSDCapacity", "SSDCapacity")
                        .WithMany("SSDCapacityLaptops")
                        .HasForeignKey("SSDCapacityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.Client", "Seller")
                        .WithMany("Laptops")
                        .HasForeignKey("SellerId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Type", "Type")
                        .WithMany("TypeLaptops")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.VideoCard", "VideoCard")
                        .WithMany("VideoCardLaptops")
                        .HasForeignKey("VideoCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("CPU");

                    b.Navigation("Color");

                    b.Navigation("DisplayCoverage");

                    b.Navigation("DisplaySize");

                    b.Navigation("DisplayTechnology");

                    b.Navigation("RAM");

                    b.Navigation("Resolution");

                    b.Navigation("SSDCapacity");

                    b.Navigation("Seller");

                    b.Navigation("Type");

                    b.Navigation("VideoCard");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Mouse", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Brand", "Brand")
                        .WithMany("BrandMice")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Color", "Color")
                        .WithMany("ColorMice")
                        .HasForeignKey("ColorId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.Client", "Seller")
                        .WithMany("Mice")
                        .HasForeignKey("SellerId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Sensitivity", "Sensitivity")
                        .WithMany("SensitivityMice")
                        .HasForeignKey("SensitivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Type", "Type")
                        .WithMany("TypeMice")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Seller");

                    b.Navigation("Sensitivity");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.SmartWatch", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Brand", "Brand")
                        .WithMany("BrandSmartWatches")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Color", "Color")
                        .WithMany("ColorSmartWatches")
                        .HasForeignKey("ColorId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.Client", "Seller")
                        .WithMany("SmartWatches")
                        .HasForeignKey("SellerId");

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Television", b =>
                {
                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Brand", "Brand")
                        .WithMany("BrandTelevisions")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Color", "Color")
                        .WithMany("ColorTelevisions")
                        .HasForeignKey("ColorId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplaySize", "DisplaySize")
                        .WithMany("DisplaySizeTelevisions")
                        .HasForeignKey("DisplaySizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplayTechnology", "DisplayTechnology")
                        .WithMany("DisplayTechnologyTelevisions")
                        .HasForeignKey("DisplayTechnologyId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Resolution", "Resolution")
                        .WithMany("ResolutionTelevisions")
                        .HasForeignKey("ResolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechStore.Infrastructure.Data.Models.Client", "Seller")
                        .WithMany("Televisions")
                        .HasForeignKey("SellerId");

                    b.HasOne("TechStore.Infrastructure.Data.Models.AttributesClasses.Type", "Type")
                        .WithMany("TypeTelevisions")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Color");

                    b.Navigation("DisplaySize");

                    b.Navigation("DisplayTechnology");

                    b.Navigation("Resolution");

                    b.Navigation("Seller");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Brand", b =>
                {
                    b.Navigation("BrandHeadphones");

                    b.Navigation("BrandKeyboards");

                    b.Navigation("BrandLaptops");

                    b.Navigation("BrandMice");

                    b.Navigation("BrandSmartWatches");

                    b.Navigation("BrandTelevisions");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.CPU", b =>
                {
                    b.Navigation("CPULaptops");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Color", b =>
                {
                    b.Navigation("ColorHeadphones");

                    b.Navigation("ColorKeyboards");

                    b.Navigation("ColorLaptops");

                    b.Navigation("ColorMice");

                    b.Navigation("ColorSmartWatches");

                    b.Navigation("ColorTelevisions");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplayCoverage", b =>
                {
                    b.Navigation("DisplayCoverageLaptops");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplaySize", b =>
                {
                    b.Navigation("DisplaySizeLaptops");

                    b.Navigation("DisplaySizeTelevisions");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.DisplayTechnology", b =>
                {
                    b.Navigation("DisplayTechnologyLaptops");

                    b.Navigation("DisplayTechnologyTelevisions");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Format", b =>
                {
                    b.Navigation("FormatKeyboards");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.RAM", b =>
                {
                    b.Navigation("RAMLaptops");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Resolution", b =>
                {
                    b.Navigation("ResolutionLaptops");

                    b.Navigation("ResolutionTelevisions");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.SSDCapacity", b =>
                {
                    b.Navigation("SSDCapacityLaptops");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Sensitivity", b =>
                {
                    b.Navigation("SensitivityMice");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.Type", b =>
                {
                    b.Navigation("TypeHeadphones");

                    b.Navigation("TypeKeyboards");

                    b.Navigation("TypeLaptops");

                    b.Navigation("TypeMice");

                    b.Navigation("TypeTelevisions");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.AttributesClasses.VideoCard", b =>
                {
                    b.Navigation("VideoCardLaptops");
                });

            modelBuilder.Entity("TechStore.Infrastructure.Data.Models.Client", b =>
                {
                    b.Navigation("Headphones");

                    b.Navigation("Keyboards");

                    b.Navigation("Laptops");

                    b.Navigation("Mice");

                    b.Navigation("SmartWatches");

                    b.Navigation("Televisions");
                });
#pragma warning restore 612, 618
        }
    }
}
